### ISSUE TITLE
下载时程序异常卡住

### ISSUE THREAD

**Issue by luo-2233** [AnzhiZhang/CurseForgeModpackDownloader#10]
下载能够正常进行，但是命令提示符窗口内容不动，未自动进行最后的自动打包
![QQ截图20220529162918](https://user-images.githubusercontent.com/104070571/170859271-27778131-5db4-4e29-84a1-70f94ad4f824.png)
![QQ图片20220529163010](https://user-images.githubusercontent.com/104070571/170859298-66009d8e-000c-41b6-9756-e7a1be0d8246.png)

**Comment by AnzhiZhang** [comment]
点击窗口按下回车
