### ISSUE TITLE
希望优化大型整合包下载

### ISSUE THREAD

**Issue by Cactusstudent** [AnzhiZhang/CurseForgeModpackDownloader#3]
能否在大型整合包下载时，不一条条弹出下载模组的提示，转而使用百分比代替。不至于过多，若出现下载失败的情况，在其余模组都下载完之后和现在一样弹出提示。

**Comment by AnzhiZhang** [comment]
使用进度条需要引入新的库，下载过程可以切到后台不用看着

**Comment by AnzhiZhang** [comment]
未来如果更新图形化界面和软件内搜索整合包/选择版本下载功能，下载会以图形界面的进度条替换
