### ISSUE TITLE
现在下载显示获取模组下载地址失败

### ISSUE THREAD

**Issue by GodLikesYou** [AnzhiZhang/CurseForgeModpackDownloader#31]
我用了vpn和clash也无法下载,用curseForge官网上下载的导入包进行导入后直接下载进度条没有动
![Snipaste_2022-07-24_12-54-15](https://user-images.githubusercontent.com/48895878/180632887-18ab6615-a2a0-4ba8-95af-a86a733b939f.png)

**Comment by AnzhiZhang** [comment]
纯粹网络问题
