### ISSUE TITLE
linux安装文件格式不正确

### ISSUE THREAD

**Issue by hanye-lun** [AnzhiZhang/CurseForgeModpackDownloader#32]
manjaro xfce下使用归档管理器解压安装文件报错 “非gzip格式” ，将后缀改为zip可以解决问题
报错原文：
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by AnzhiZhang** [comment]
不提供 linux 支持，请自行解决，欢迎 PR
