### ISSUE TITLE
http端口重复开启

### ISSUE THREAD

**Issue by Coloryr** [AnzhiZhang/CurseForgeModpackDownloader#33]
~虽然我感觉这也不是什么大问题，但它这样感觉多少会出问题~
![81T@)KKPQI$Q1%T}O92FXEJ](https://user-images.githubusercontent.com/26276037/184628729-013b526d-f566-4dc5-a19d-e4b701089195.png)

**Comment by AnzhiZhang** [comment]
这个是因为使用了多线程，开多个端口是正常的

**Comment by Coloryr** [comment]
关键是一直重复开启和关闭

**Comment by AnzhiZhang** [comment]
每下载一个模组就是一个新的连接
