### ISSUE TITLE
Fabric 整合包支持

### ISSUE THREAD

**Issue by HanlieChina** [AnzhiZhang/CurseForgeModpackDownloader#4]
实例更新失败，因为：组件元数据更新失败，在从远端服务器下载时出现错误：
任务“下载元数据文件 net.minecraftforge/fabric-0.14.5.json”处理失败：
https://meta.multimc.org/v1/net.minecraftforge/fabric-0.14.5.json。

**Comment by AnzhiZhang** [comment]
暂时未支持fabric整合包，能否提供整合包名称？

**Comment by AnzhiZhang** [comment]
目前有报告的不支持的 fabric 整合包：
[Darkrpg](https://www.curseforge.com/minecraft/modpacks/darkrpg)
https://www.bilibili.com/read/cv16750614#reply114073600304

**Comment by HanlieChina** [comment]
> 暂时未支持fabric整合包，能否提供整合包名称？

[Valhelsia: Enhanced Vanilla - 1.18](https://www.curseforge.com/minecraft/modpacks/valhelsia-enhanced-vanilla)

当然只要手动在编辑实例中删除错误的版本即可。

**Comment by AnzhiZhang** [comment]
是的，在生成的版本中硬编码了forge，没有做识别
