### ISSUE TITLE
"Program couldn't be started because api-ms-win-core-path-l1-1-0.dll is missing"

### ISSUE THREAD

**Issue by TouhouJevil** [AnzhiZhang/CurseForgeModpackDownloader#43]
I keep getting this error saying api-ms-win-core-path-l1-1-0.dll is missing or couldn't be found, something i want to point is that i have already ALL vcredit files installed from microsoft and even tried reinstalling them and didn't work at all, then i went and tried to download the file from other websites but i just get another error that says "error message couldn't be generated", i'm using windows 7 64 bits professional.

**Comment by AnzhiZhang** [comment]
Sorry I have no idea with this issue, but I will leave this issue open if someone else could help you.

It may required by the binary file, it works well on win 11/10. You could try install Python (https://www.python.org/downloads/) and run source code.

**Comment by choulily** [comment]
It seems newer version of python does not support Windows 7. Although our packer is setting up python 3.10 but it is not working for some reason.
Sorry we have no solution but update Windows.
[Software based on Python 3.9 is not working on Windows 7](https://stackoverflow.com/questions/66718131/software-based-on-python-3-9-is-not-working-on-windows-7)
